env:
  browser: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - warn
    - always
  no-console: 0
  no-unused-vars: 1